#!/usr/bin/env python3
"""
Train an ABMIL classifier on precomputed patch embeddings.

Required inputs:
  - embeddings_with_labels.csv (generated by extract_embeddings.py)
  - attention weights and slide vectors will be written to outputs.
"""

from __future__ import annotations

import argparse
import json
import logging
import re
from collections import Counter
from pathlib import Path
from typing import Any, Dict, List, Optional, Sequence, Tuple

import numpy as np
import pandas as pd
import torch
import torch.nn.functional as F
from torch.utils.data import DataLoader, Dataset
from tqdm.auto import tqdm

SCRIPT_DIR = Path(__file__).resolve().parent
SRC_ROOT = SCRIPT_DIR.parent

import sys

if str(SRC_ROOT) not in sys.path:
    sys.path.insert(0, str(SRC_ROOT))

from utils.path import ensure_project_root_on_syspath, resolve_path, get_project_root  # noqa: E402
from models.Classification.abmil import ABMIL  # noqa: E402

ensure_project_root_on_syspath()
PROJECT_ROOT = get_project_root()
LOG_DIR = PROJECT_ROOT / "outputs" / "logs"

LABEL_PATTERN = re.compile(r"\d+")


def _extract_label(value: Any) -> Optional[int]:
    if pd.isna(value):
        return None
    raw = str(value).strip()
    if raw.lower() in {"", "nan", "none"}:
        return None
    match = LABEL_PATTERN.search(raw)
    if match is None:
        logging.warning("Unable to parse label value '%s'", raw)
        return None
    return int(match.group(0))


class SlideBagDataset(Dataset):
    """Dataset returning one bag (slide) of embeddings per item."""

    def __init__(
        self,
        frame: pd.DataFrame,
        entries: Optional[List[Tuple[str, int, List[str], List[str]]]] = None,
    ) -> None:
        self.frame = frame
        if entries is not None:
            self.entries = entries
        else:
            groups = frame.groupby("slide_id")
            self.entries = []
            for slide_id, group in groups:
                label_value = _extract_label(group["label"].iloc[0])
                if label_value is None:
                    logging.warning("Skipping slide_id=%s due to unparseable label '%s'", slide_id, group["label"].iloc[0])
                    continue
                label = label_value
                embed_paths = group["embedding_path"].tolist()
                if not embed_paths:
                    logging.warning("Skipping slide_id=%s because no embedding paths are available", slide_id)
                    continue
                patch_paths = group["patch_path"].tolist()
                self.entries.append((slide_id, label, patch_paths, embed_paths))

    def subset(self, indices: Sequence[int]) -> "SlideBagDataset":
        subset_entries = [self.entries[i] for i in indices]
        return SlideBagDataset(self.frame, subset_entries)

    def __len__(self) -> int:
        return len(self.entries)

    def __getitem__(self, idx: int) -> Tuple[str, int, torch.Tensor, List[str], List[str]]:
        slide_id, label, patch_paths, embed_paths = self.entries[idx]
        feats = [np.load(resolve_path(p)).astype(np.float32).reshape(-1) for p in embed_paths]
        bag = torch.from_numpy(np.stack(feats, axis=0))
        return slide_id, label, bag, patch_paths, embed_paths


def collate_fn(batch):
    slide_ids, labels, bags, patch_paths, embed_paths = zip(*batch)
    return list(slide_ids), torch.tensor(labels), list(bags), list(patch_paths), list(embed_paths)


def train(args: argparse.Namespace) -> None:
    logging.info("Loading embeddings from %s", args.embeddings_csv)
    embeddings_df = pd.read_csv(resolve_path(args.embeddings_csv))
    if {"patch_path", "embedding_path"} - set(embeddings_df.columns):
        raise ValueError("embeddings CSV must contain 'patch_path' and 'embedding_path' columns.")

    logging.info("Loading metadata from %s", args.metadata_csv)
    metadata_df = pd.read_csv(resolve_path(args.metadata_csv))
    if {"patch_path", "stain_id", "Reticulin Grade", "type"} - set(metadata_df.columns):
        raise ValueError("metadata CSV missing required columns (patch_path, stain_id, Reticulin Grade, type).")

    metadata_df = metadata_df[metadata_df["type"].astype(str).str.lower().str.contains("reticulin")].copy()
    metadata_df["patch_path_norm"] = metadata_df["patch_path"].astype(str).str.replace("\\", "/", regex=False)
    metadata_df = metadata_df.dropna(subset=["Reticulin Grade"])
    metadata_df["label"] = metadata_df["Reticulin Grade"].apply(_extract_label)
    metadata_df = metadata_df.dropna(subset=["label"])
    metadata_df["label"] = metadata_df["label"].astype(int)
    metadata_df["slide_id"] = metadata_df["stain_id"].astype(str)

    embeddings_df = embeddings_df.copy()
    embeddings_df["patch_path_norm"] = embeddings_df["patch_path"].astype(str).str.replace("\\", "/", regex=False)

    df = embeddings_df.merge(
        metadata_df[["patch_path_norm", "slide_id", "label"]],
        on="patch_path_norm",
        how="inner",
    )
    if df.empty:
        raise ValueError("No overlap between embeddings CSV and metadata (after Reticulin filter).")
    missing = len(embeddings_df) - len(df)
    if missing > 0:
        logging.warning("Dropped %d embedding rows without Reticulin metadata match.", missing)

    df = df[["slide_id", "label", "patch_path", "embedding_path"]]

    full_dataset = SlideBagDataset(df)
    logging.info("Prepared %d slide_id-label pairs", len(full_dataset))
    num_slides = len(full_dataset)
    if num_slides == 0:
        raise ValueError("No slides found in embeddings CSV.")

    rng = np.random.default_rng(args.seed)
    label_to_indices: dict[int, list[int]] = {}
    for idx, (_, label, _, _) in enumerate(full_dataset.entries):
        label_to_indices.setdefault(int(label), []).append(idx)

    split_map: Optional[dict[str, str]] = None
    if args.augmented_slides and args.augmented_splits:
        split_map = load_split_map(Path(args.augmented_slides), Path(args.augmented_splits))
        logging.info(
            "Using augmented splits (%s, %s) with %d mapped slide IDs.",
            args.augmented_slides,
            args.augmented_splits,
            len(split_map),
        )

    train_indices: list[int] = []
    val_indices: list[int] = []

    if split_map:
        skipped_reasons: Dict[str, List[str]] = {
            "test": [],
            "missing_in_augmented_mapping": [],
            "unknown_split": [],
        }

        for idx, (slide_id, _, _, _) in enumerate(full_dataset.entries):
            split = split_map.get(slide_id)
            if split == "train":
                train_indices.append(idx)
            elif split == "val":
                val_indices.append(idx)
            elif split == "test":
                skipped_reasons["test"].append(slide_id)
            elif split is None:
                skipped_reasons["missing_in_augmented_mapping"].append(slide_id)
            else:
                skipped_reasons["unknown_split"].append(slide_id)

        skipped = sum(len(v) for v in skipped_reasons.values())

        if not train_indices:
            raise ValueError("Augmented split mapping produced an empty training set.")

        logging.info(
            "Augmented split counts | train=%d | val=%d | skipped=%d",
            len(train_indices),
            len(val_indices),
            skipped,
        )

        for reason, slides in skipped_reasons.items():
            if slides:
                logging.info(
                    "  skipped (%s): %d slides",
                    reason,
                    len(slides),
                )

        # write detailed skipped list
        skipped_rows = []
        for reason, slides in skipped_reasons.items():
            for sid in slides:
                skipped_rows.append({"slide_id": sid, "reason": reason})

        if skipped_rows:
            skipped_csv = PROJECT_ROOT / "outputs" / "analysis" / "train_classifier_skipped_slides.csv"
            skipped_csv.parent.mkdir(parents=True, exist_ok=True)
            pd.DataFrame(skipped_rows).to_csv(skipped_csv, index=False)
            logging.info("Wrote skipped slide details to %s", skipped_csv)

        train_label_counts = Counter(int(full_dataset.entries[i][1]) for i in train_indices)
        val_label_counts = Counter(int(full_dataset.entries[i][1]) for i in val_indices)
    else:
        train_label_counts: Counter[int] = Counter()
        val_label_counts: Counter[int] = Counter()
        for label, idx_list in label_to_indices.items():
            idx_array = np.array(idx_list, dtype=int)
            rng.shuffle(idx_array)
            count = len(idx_array)
            desired_val = int(count * args.val_ratio)
            if args.val_ratio > 0 and desired_val == 0 and count > 1:
                desired_val = 1
            if desired_val >= count:
                desired_val = max(0, count - 1)

            val_split = idx_array[:desired_val].tolist() if desired_val > 0 else []
            train_split = idx_array[desired_val:].tolist()

            val_indices.extend(val_split)
            train_indices.extend(train_split)

            val_label_counts[label] += len(val_split)
            train_label_counts[label] += len(train_split)

    if not train_indices:
        raise ValueError("Training split is empty after stratified sampling.")

    train_dataset = full_dataset.subset(train_indices)
    val_dataset = full_dataset.subset(val_indices) if val_indices else None

    logging.info(
        "Stratified split | train label counts: %s | val label counts: %s",
        dict(sorted(train_label_counts.items())),
        dict(sorted(val_label_counts.items())),
    )

    train_loader = DataLoader(train_dataset, batch_size=args.batch_size, shuffle=True, collate_fn=collate_fn)
    val_loader = DataLoader(val_dataset, batch_size=args.batch_size, shuffle=False, collate_fn=collate_fn) if val_dataset else None

    feat_dim = train_dataset[0][2].shape[1]
    logging.info("Slides: %d (train=%d, val=%d) | Feature dim: %d", num_slides, len(train_dataset), len(val_dataset or []), feat_dim)

    model = ABMIL(
        in_dim=feat_dim,
        attn_dim=args.att_dim,
        classifier_hidden=args.hidden_dim,
        num_classes=args.num_classes,
        dropout=args.dropout,
    ).to(args.device)

    if args.weight_file:
        state = torch.load(resolve_path(args.weight_file), map_location="cpu")
        model.classifier.load_state_dict(state)
        logging.info("Loaded classifier weights from %s", args.weight_file)

    optimizer = torch.optim.AdamW(model.parameters(), lr=args.lr, weight_decay=args.weight_decay)

    history: list[dict[str, float]] = []
    best_val_loss = float("inf")
    best_epoch = 0
    best_state: Optional[dict[str, dict[str, torch.Tensor]]] = None

    checkpoints_dir = PROJECT_ROOT / "outputs" / "checkpoints" / "abmil"
    checkpoints_dir.mkdir(parents=True, exist_ok=True)
    abmil_last_path = checkpoints_dir / f"{args.run_name}_abmil_last.pt"
    classifier_last_path = checkpoints_dir / f"{args.run_name}_classifier_last.pt"
    abmil_best_path = checkpoints_dir / f"{args.run_name}_abmil_best.pt"
    classifier_best_path = checkpoints_dir / f"{args.run_name}_classifier_best.pt"

    def run_epoch(loader: DataLoader, train: bool) -> Tuple[float, float, List[float], float, float]:
        if loader is None:
            return (
                float("nan"),
                float("nan"),
                [float("nan")] * args.num_classes,
                float("nan"),
                float("nan"),
            )
        epoch_loss = 0.0
        correct = 0
        total = 0
        conf_matrix = np.zeros((args.num_classes, args.num_classes), dtype=np.int64)
        if train:
            model.train()
        else:
            model.eval()
        for _, labels, bags, _, _ in loader:
            labels = labels.to(args.device)
            bags = [bag.to(args.device) for bag in bags]

            if train:
                optimizer.zero_grad()
                logits, _, _ = model(bags)
                loss = F.cross_entropy(logits, labels)
                loss.backward()
                optimizer.step()
            else:
                with torch.no_grad():
                    logits, _, _ = model(bags)
                    loss = F.cross_entropy(logits, labels)

            epoch_loss += loss.item() * labels.size(0)
            preds = logits.argmax(dim=1)
            correct += (preds == labels).sum().item()
            total += labels.size(0)
            labels_np = labels.detach().cpu().numpy()
            preds_np = preds.detach().cpu().numpy()
            for true_val, pred_val in zip(labels_np, preds_np):
                if 0 <= true_val < args.num_classes and 0 <= pred_val < args.num_classes:
                    conf_matrix[true_val, pred_val] += 1

        avg_loss = epoch_loss / total if total else float("nan")
        overall_acc = correct / total if total else float("nan")

        class_total = conf_matrix.sum(axis=1)
        class_correct = np.diag(conf_matrix)
        class_acc = [
            (class_correct[i] / class_total[i]) if class_total[i] else float("nan")
            for i in range(args.num_classes)
        ]

        fp = conf_matrix.sum(axis=0) - class_correct
        fn = class_total - class_correct
        denom = (2 * class_correct + fp + fn).astype(np.float64)
        per_class_f1 = np.where(denom > 0, (2 * class_correct) / denom, np.nan)
        macro_f1 = float(np.nanmean(per_class_f1)) if np.any(~np.isnan(per_class_f1)) else float("nan")

        total_obs = conf_matrix.sum()
        qwk = float("nan")
        if total_obs:
            hist_true = class_total.astype(np.float64)
            hist_pred = conf_matrix.sum(axis=0).astype(np.float64)
            expected = np.outer(hist_true, hist_pred)
            expected_sum = expected.sum()
            if expected_sum > 0:
                expected = expected / expected_sum
                observed = conf_matrix.astype(np.float64) / total_obs
                if args.num_classes > 1:
                    denom_weights = float((args.num_classes - 1) ** 2)
                else:
                    denom_weights = 1.0
                rows = np.arange(args.num_classes)[:, None]
                cols = np.arange(args.num_classes)[None, :]
                weights = ((rows - cols) ** 2).astype(np.float64) / denom_weights
                expected_weighted = float((weights * expected).sum())
                observed_weighted = float((weights * observed).sum())
                if expected_weighted > 0:
                    qwk = 1.0 - observed_weighted / expected_weighted

        return avg_loss, overall_acc, class_acc, macro_f1, qwk

    interrupted = False
    epoch = 0
    try:
        for epoch in range(1, args.epochs + 1):
            (
                train_loss,
                train_acc,
                train_class_acc,
                train_macro_f1,
                train_qwk,
            ) = run_epoch(train_loader, train=True)
            if val_loader:
                (
                    val_loss,
                    val_acc,
                    val_class_acc,
                    val_macro_f1,
                    val_qwk,
                ) = run_epoch(val_loader, train=False)
            else:
                val_loss = float("nan")
                val_acc = float("nan")
                val_class_acc = [float("nan")] * args.num_classes
                val_macro_f1 = float("nan")
                val_qwk = float("nan")

            train_entry = {
                "epoch": epoch,
                "split": "train",
                "loss": train_loss,
                "accuracy": train_acc,
                "macro_f1": train_macro_f1,
                "qwk": train_qwk,
            }
            for cls_idx, cls_acc in enumerate(train_class_acc):
                train_entry[f"accuracy_cls{cls_idx}"] = cls_acc
            history.append(train_entry)

            if not np.isnan(val_loss):
                val_entry = {
                    "epoch": epoch,
                    "split": "val",
                    "loss": val_loss,
                    "accuracy": val_acc,
                    "macro_f1": val_macro_f1,
                    "qwk": val_qwk,
                }
                for cls_idx, cls_acc in enumerate(val_class_acc):
                    val_entry[f"accuracy_cls{cls_idx}"] = cls_acc
                history.append(val_entry)

                if val_loss < best_val_loss:
                    best_val_loss = val_loss
                    best_epoch = epoch
                    best_state = {
                        "model": {k: v.cpu() for k, v in model.state_dict().items()},
                        "classifier": {k: v.cpu() for k, v in model.classifier.state_dict().items()},
                    }

            log_parts = [
                f"Epoch {epoch:02d}",
                f"train_loss={train_loss:.4f}",
                f"train_acc={train_acc:.3f}",
            ]
            if not np.isnan(train_macro_f1):
                log_parts.append(f"train_f1={train_macro_f1:.3f}")
            if not np.isnan(train_qwk):
                log_parts.append(f"train_qwk={train_qwk:.3f}")
            if not np.isnan(val_loss):
                log_parts.extend([
                    f"val_loss={val_loss:.4f}",
                    f"val_acc={val_acc:.3f}",
                ])
                if not np.isnan(val_macro_f1):
                    log_parts.append(f"val_f1={val_macro_f1:.3f}")
                if not np.isnan(val_qwk):
                    log_parts.append(f"val_qwk={val_qwk:.3f}")
            logging.info(" | ".join(log_parts))

            def _format_class_acc(accs: Sequence[float]) -> str:
                parts = []
                for idx, acc in enumerate(accs):
                    if np.isnan(acc):
                        parts.append(f"c{idx}=nan")
                    else:
                        parts.append(f"c{idx}={acc:.3f}")
                return ", ".join(parts)

            logging.info("    train per-class acc: %s", _format_class_acc(train_class_acc))
            if not np.isnan(val_loss):
                logging.info("    val   per-class acc: %s", _format_class_acc(val_class_acc))

            if args.save_every and args.save_every > 0 and (epoch % args.save_every == 0):
                epoch_abmil_path = checkpoints_dir / f"{args.run_name}_abmil_epoch{epoch:03d}.pt"
                epoch_classifier_path = checkpoints_dir / f"{args.run_name}_classifier_epoch{epoch:03d}.pt"
                torch.save(model.state_dict(), epoch_abmil_path)
                torch.save(model.classifier.state_dict(), epoch_classifier_path)
                logging.info("Saved periodic checkpoints at epoch %d to %s and %s", epoch, epoch_abmil_path, epoch_classifier_path)
    except KeyboardInterrupt:
        interrupted = True
        logging.warning("Training interrupted at epoch %d", epoch)

    if interrupted:
        logging.info("Proceeding to export artifacts after interruption.")

    output_dir = resolve_path(args.output_dir, allow_missing=True)
    output_dir.mkdir(parents=True, exist_ok=True)

    attention_rows = []
    slide_rows = []

    model.eval()
    with torch.no_grad():
        for slide_id, label, bag, patch_paths, embed_paths in full_dataset:
            bag = bag.to(args.device)
            logits, attn, slide_vec = model.forward_one(bag)
            attn = attn.cpu().numpy()
            slide_vec = slide_vec.cpu().numpy().astype(np.float32)

            for patch_path, embed_path, weight in zip(patch_paths, embed_paths, attn):
                attention_rows.append(
                    {
                        "slide_id": slide_id,
                        "patch_path": patch_path,
                        "embedding_path": embed_path,
                        "attention_weight": float(weight),
                        "label": int(label),
                    }
                )

            vector_path = output_dir / f"{slide_id}.npy"
            np.save(vector_path, slide_vec)
            slide_rows.append({"slide_id": slide_id, "label": int(label), "vector_path": str(vector_path)})

    attention_csv = output_dir / "attention_weights.csv"
    slide_csv = output_dir / "slide_vectors.csv"
    torch.save(model.state_dict(), abmil_last_path)
    torch.save(model.classifier.state_dict(), classifier_last_path)

    if best_state is not None:
        torch.save(best_state["model"], abmil_best_path)
        torch.save(best_state["classifier"], classifier_best_path)
    else:
        abmil_best_path = None
        classifier_best_path = None

    pd.DataFrame(attention_rows).to_csv(attention_csv, index=False)
    pd.DataFrame(slide_rows).to_csv(slide_csv, index=False)

    metrics_df = pd.DataFrame(history)
    metrics_csv = output_dir / "training_metrics.csv"
    metrics_df.to_csv(metrics_csv, index=False)

    try:
        import matplotlib.pyplot as plt

        epochs = sorted(set(metrics_df["epoch"]))
        def plot_metric(metric: str, ylabel: str, filename: str) -> None:
            plt.figure()
            for split in metrics_df["split"].unique():
                split_df = metrics_df[metrics_df["split"] == split]
                plt.plot(split_df["epoch"], split_df[metric], label=split)
            plt.xlabel("Epoch")
            plt.ylabel(ylabel)
            plt.title(f"{ylabel} over epochs")
            plt.legend()
            plt.grid(True, linestyle="--", alpha=0.4)
            plt.tight_layout()
            plt.savefig(output_dir / filename)
            plt.close()

        if len(epochs) > 0:
            plot_metric("loss", "Loss", "loss_curve.png")
            plot_metric("accuracy", "Accuracy", "accuracy_curve.png")
    except Exception as exc:
        logging.warning("Failed to save plots: %s", exc)

    logging.info("Saved attention weights to %s", attention_csv)
    logging.info("Saved slide vectors to %s", slide_csv)
    logging.info("Saved metrics to %s", metrics_csv)
    logging.info("Saved last ABMIL weights to %s", abmil_last_path)
    logging.info("Saved last classifier weights to %s", classifier_last_path)
    if best_state is not None:
        logging.info("Best epoch: %d | val_loss=%.4f", best_epoch, best_val_loss)
        logging.info("Saved best ABMIL weights to %s", abmil_best_path)
        logging.info("Saved best classifier weights to %s", classifier_best_path)


DEFAULT_CONFIG = PROJECT_ROOT / "configs" / "train_classifier.json"


def _load_json_config(path: Path) -> dict[str, Any]:
    if not path.exists():
        return {}
    data = json.loads(path.read_text("utf-8"))
    if not isinstance(data, dict):
        raise ValueError(f"Config file {path} must contain a JSON object.")
    return data


def load_split_map(slides_path: Path, splits_path: Path) -> Dict[str, str]:
    slides = json.loads(Path(slides_path).read_text("utf-8"))
    splits = json.loads(Path(splits_path).read_text("utf-8"))
    mapping: Dict[str, str] = {}

    def _assign(indices: Sequence[int], split_name: str) -> None:
        for idx in indices:
            if 0 <= idx < len(slides):
                entry = slides[idx]
                slide_id = str(
                    entry.get("ret_stain_id")
                    or entry.get("he_stain_id")
                    or entry.get("stain_id")
                    or ""
                ).strip()
                if slide_id:
                    mapping[slide_id] = split_name

    _assign(splits.get("train_indices", []), "train")
    _assign(splits.get("val_indices", []), "val")
    _assign(splits.get("test_indices", []), "test")
    return mapping


def parse_args(argv: Sequence[str] | None = None) -> argparse.Namespace:
    base = argparse.ArgumentParser(add_help=False)
    base.add_argument("--config", type=str, default=str(DEFAULT_CONFIG))
    config_ns, remaining = base.parse_known_args(argv)
    config = _load_json_config(Path(config_ns.config))

    parser = argparse.ArgumentParser(description="Train ABMIL classifier on precomputed embeddings.", parents=[base])
    parser.add_argument("--embeddings-csv", type=str, default=config.get("embeddings_csv"))
    parser.add_argument("--metadata-csv", type=str, default=config.get("metadata_csv"))
    parser.add_argument("--output-dir", type=str, default=config.get("output_dir"))
    parser.add_argument("--run-name", type=str, default=config.get("run_name", "abmil"))
    parser.add_argument("--epochs", type=int, default=config.get("epochs", 30))
    parser.add_argument("--lr", type=float, default=config.get("lr", 1e-4))
    parser.add_argument("--weight-decay", type=float, default=config.get("weight_decay", 1e-4))
    parser.add_argument("--att-dim", type=int, default=config.get("att_dim", 256))
    parser.add_argument("--hidden-dim", type=int, default=config.get("hidden_dim", 512))
    parser.add_argument("--dropout", type=float, default=config.get("dropout", 0.25))
    parser.add_argument("--num-classes", type=int, default=config.get("num_classes", 4))
    parser.add_argument("--batch-size", type=int, default=config.get("batch_size", 1), help="Bags per batch.")
    parser.add_argument("--device", type=str, default=config.get("device"))
    parser.add_argument("--weight-file", type=str, default=config.get("weight_file"))
    parser.add_argument("--val-ratio", type=float, default=config.get("val_ratio", 0.2))
    parser.add_argument("--seed", type=int, default=config.get("seed", 42))
    parser.add_argument("--log-level", type=str, default=config.get("log_level", "INFO"))
    parser.add_argument("--save-every", type=int, default=config.get("save_every", 5))
    parser.add_argument("--augmented-slides", type=str, default=config.get("augmented_slides"))
    parser.add_argument("--augmented-splits", type=str, default=config.get("augmented_splits"))
    args = parser.parse_args(remaining)
    if not args.embeddings_csv or not args.metadata_csv or not args.output_dir:
        parser.error("Specify --embeddings-csv, --metadata-csv, and --output-dir (CLI or config).")
    args.embeddings_csv = resolve_path(args.embeddings_csv)
    args.metadata_csv = resolve_path(args.metadata_csv)
    args.output_dir = resolve_path(args.output_dir, allow_missing=True)
    if args.weight_file:
        args.weight_file = resolve_path(args.weight_file)
    if args.augmented_slides:
        args.augmented_slides = resolve_path(args.augmented_slides)
    if args.augmented_splits:
        args.augmented_splits = resolve_path(args.augmented_splits)
    return args


def main(argv: Sequence[str] | None = None) -> None:
    args = parse_args(argv)

    if args.device is None:
        if torch.cuda.is_available():
            args.device = "cuda"
        elif getattr(torch.backends, "mps", None) and torch.backends.mps.is_available():
            args.device = "mps"
        else:
            args.device = "cpu"

    LOG_DIR.mkdir(parents=True, exist_ok=True)
    log_file = LOG_DIR / f"{args.run_name}.log"
    logging.basicConfig(
        level=getattr(logging, args.log_level.upper(), logging.INFO),
        format="%(asctime)s [%(levelname)s] %(message)s",
        handlers=[
            logging.StreamHandler(),
            logging.FileHandler(log_file, mode="w"),
        ],
    )
    logging.info("Writing log to %s", log_file)
    logging.info("Arguments: %s", json.dumps(vars(args), indent=2, default=str))

    train(args)


if __name__ == "__main__":
    main()

