#!/usr/bin/env python3
"""
Train an ABMIL classifier on precomputed patch embeddings.

Required inputs:
  - embeddings_with_labels.csv (generated by extract_embeddings.py)
  - attention weights and slide vectors will be written to outputs.
"""

from __future__ import annotations

import argparse
import json
import logging
from pathlib import Path
from typing import List, Sequence, Tuple, Optional

import numpy as np
import pandas as pd
import torch
import torch.nn.functional as F
from torch.utils.data import DataLoader, Dataset
from tqdm.auto import tqdm

SCRIPT_DIR = Path(__file__).resolve().parent
SRC_ROOT = SCRIPT_DIR.parent

import sys

if str(SRC_ROOT) not in sys.path:
    sys.path.insert(0, str(SRC_ROOT))

from utils.path import ensure_project_root_on_syspath, resolve_path, get_project_root  # noqa: E402
from models.Classification.abmil import ABMIL  # noqa: E402

ensure_project_root_on_syspath()
PROJECT_ROOT = get_project_root()
LOG_DIR = PROJECT_ROOT / "outputs" / "logs"


class SlideBagDataset(Dataset):
    """Dataset returning one bag (slide) of embeddings per item."""

    def __init__(
        self,
        frame: pd.DataFrame,
        entries: Optional[List[Tuple[str, int, List[str], List[str]]]] = None,
    ) -> None:
        self.frame = frame
        if entries is not None:
            self.entries = entries
        else:
            groups = frame.groupby("slide_id")
            self.entries = []
            for slide_id, group in groups:
                label = int(group["label"].iloc[0])
                embed_paths = group["embedding_path"].tolist()
                patch_paths = group["patch_path"].tolist()
                self.entries.append((slide_id, label, patch_paths, embed_paths))

    def subset(self, indices: Sequence[int]) -> "SlideBagDataset":
        subset_entries = [self.entries[i] for i in indices]
        return SlideBagDataset(self.frame, subset_entries)

    def __len__(self) -> int:
        return len(self.entries)

    def __getitem__(self, idx: int) -> Tuple[str, int, torch.Tensor, List[str], List[str]]:
        slide_id, label, patch_paths, embed_paths = self.entries[idx]
        feats = [np.load(resolve_path(p)).astype(np.float32).reshape(-1) for p in embed_paths]
        bag = torch.from_numpy(np.stack(feats, axis=0))
        return slide_id, label, bag, patch_paths, embed_paths


def collate_fn(batch):
    slide_ids, labels, bags, patch_paths, embed_paths = zip(*batch)
    return list(slide_ids), torch.tensor(labels), list(bags), list(patch_paths), list(embed_paths)


def train(args: argparse.Namespace) -> None:
    logging.info("Loading embeddings from %s", args.embeddings_csv)
    embeddings_df = pd.read_csv(resolve_path(args.embeddings_csv))
    if {"patch_path", "embedding_path"} - set(embeddings_df.columns):
        raise ValueError("embeddings CSV must contain 'patch_path' and 'embedding_path' columns.")

    logging.info("Loading metadata from %s", args.metadata_csv)
    metadata_df = pd.read_csv(resolve_path(args.metadata_csv))
    if {"patch_path", "stain_id", "Reticulin Grade", "type"} - set(metadata_df.columns):
        raise ValueError("metadata CSV missing required columns (patch_path, stain_id, Reticulin Grade, type).")

    metadata_df = metadata_df.copy()
    metadata_df["patch_path_norm"] = metadata_df["patch_path"].astype(str).str.replace("\\", "/", regex=False)
    metadata_df = metadata_df[metadata_df["type"].astype(str).str.lower().str.contains("reticulin")]
    metadata_df = metadata_df.dropna(subset=["Reticulin Grade"])
    metadata_df["label"] = pd.to_numeric(metadata_df["Reticulin Grade"], errors="coerce")
    metadata_df = metadata_df.dropna(subset=["label"])
    metadata_df["label"] = metadata_df["label"].astype(int)
    metadata_df["slide_id"] = metadata_df["stain_id"].astype(str)

    embeddings_df = embeddings_df.copy()
    embeddings_df["patch_path_norm"] = embeddings_df["patch_path"].astype(str).str.replace("\\", "/", regex=False)

    df = embeddings_df.merge(
        metadata_df[["patch_path_norm", "slide_id", "label"]],
        on="patch_path_norm",
        how="inner",
    )
    if df.empty:
        raise ValueError("No overlap between embeddings CSV and metadata (after Reticulin filter).")
    missing = len(embeddings_df) - len(df)
    if missing > 0:
        logging.warning("Dropped %d embedding rows without Reticulin metadata match.", missing)

    df = df[["slide_id", "label", "patch_path", "embedding_path"]]

    full_dataset = SlideBagDataset(df)
    num_slides = len(full_dataset)
    if num_slides == 0:
        raise ValueError("No slides found in embeddings CSV.")

    rng = np.random.default_rng(args.seed)
    indices = np.arange(num_slides)
    rng.shuffle(indices)

    val_count = int(num_slides * args.val_ratio)
    val_indices = indices[:val_count]
    train_indices = indices[val_count:]

    train_dataset = full_dataset.subset(train_indices)
    val_dataset = full_dataset.subset(val_indices) if val_count > 0 else None

    train_loader = DataLoader(train_dataset, batch_size=args.batch_size, shuffle=True, collate_fn=collate_fn)
    val_loader = DataLoader(val_dataset, batch_size=args.batch_size, shuffle=False, collate_fn=collate_fn) if val_dataset else None

    feat_dim = train_dataset[0][2].shape[1]
    logging.info("Slides: %d (train=%d, val=%d) | Feature dim: %d", num_slides, len(train_dataset), len(val_dataset or []), feat_dim)

    model = ABMIL(
        in_dim=feat_dim,
        attn_dim=args.att_dim,
        classifier_hidden=args.hidden_dim,
        num_classes=args.num_classes,
        dropout=args.dropout,
    ).to(args.device)

    if args.weight_file:
        state = torch.load(resolve_path(args.weight_file), map_location="cpu")
        model.classifier.load_state_dict(state)
        logging.info("Loaded classifier weights from %s", args.weight_file)

    optimizer = torch.optim.AdamW(model.parameters(), lr=args.lr, weight_decay=args.weight_decay)

    history: list[dict[str, float]] = []
    best_val_loss = float("inf")
    best_epoch = 0
    best_state: Optional[dict[str, dict[str, torch.Tensor]]] = None

    def run_epoch(loader: DataLoader, train: bool) -> Tuple[float, float]:
        if loader is None:
            return float("nan"), float("nan")
        epoch_loss = 0.0
        correct = 0
        total = 0
        if train:
            model.train()
        else:
            model.eval()
        for _, labels, bags, _, _ in loader:
            labels = labels.to(args.device)
            bags = [bag.to(args.device) for bag in bags]

            if train:
                optimizer.zero_grad()
                logits, _, _ = model(bags)
                loss = F.cross_entropy(logits, labels)
                loss.backward()
                optimizer.step()
            else:
                with torch.no_grad():
                    logits, _, _ = model(bags)
                    loss = F.cross_entropy(logits, labels)

            epoch_loss += loss.item() * labels.size(0)
            preds = logits.argmax(dim=1)
            correct += (preds == labels).sum().item()
            total += labels.size(0)
        return epoch_loss / total if total else float("nan"), correct / total if total else float("nan")

    for epoch in range(1, args.epochs + 1):
        train_loss, train_acc = run_epoch(train_loader, train=True)
        val_loss, val_acc = run_epoch(val_loader, train=False) if val_loader else (float("nan"), float("nan"))

        history.append(
            {
                "epoch": epoch,
                "split": "train",
                "loss": train_loss,
                "accuracy": train_acc,
            }
        )
        if not np.isnan(val_loss):
            history.append(
                {
                    "epoch": epoch,
                    "split": "val",
                    "loss": val_loss,
                    "accuracy": val_acc,
                }
            )
            if val_loss < best_val_loss:
                best_val_loss = val_loss
                best_epoch = epoch
                best_state = {
                    "model": {k: v.cpu() for k, v in model.state_dict().items()},
                    "classifier": {k: v.cpu() for k, v in model.classifier.state_dict().items()},
                }

        log_msg = f"Epoch {epoch:02d} | train_loss={train_loss:.4f} train_acc={train_acc:.3f}"
        if not np.isnan(val_loss):
            log_msg += f" | val_loss={val_loss:.4f} val_acc={val_acc:.3f}"
        logging.info(log_msg)

    output_dir = resolve_path(args.output_dir, allow_missing=True)
    output_dir.mkdir(parents=True, exist_ok=True)

    attention_rows = []
    slide_rows = []

    model.eval()
    with torch.no_grad():
        for slide_id, label, bag, patch_paths, embed_paths in full_dataset:
            bag = bag.to(args.device)
            logits, attn, slide_vec = model.forward_one(bag)
            attn = attn.cpu().numpy()
            slide_vec = slide_vec.cpu().numpy().astype(np.float32)

            for patch_path, embed_path, weight in zip(patch_paths, embed_paths, attn):
                attention_rows.append(
                    {
                        "slide_id": slide_id,
                        "patch_path": patch_path,
                        "embedding_path": embed_path,
                        "attention_weight": float(weight),
                        "label": int(label),
                    }
                )

            vector_path = output_dir / f"{slide_id}.npy"
            np.save(vector_path, slide_vec)
            slide_rows.append({"slide_id": slide_id, "label": int(label), "vector_path": str(vector_path)})

    attention_csv = output_dir / "attention_weights.csv"
    slide_csv = output_dir / "slide_vectors.csv"
    checkpoints_dir = PROJECT_ROOT / "outputs" / "checkpoints" / "abmil"
    checkpoints_dir.mkdir(parents=True, exist_ok=True)
    abmil_last_path = checkpoints_dir / f"{args.run_name}_abmil_last.pt"
    classifier_last_path = checkpoints_dir / f"{args.run_name}_classifier_last.pt"
    torch.save(model.state_dict(), abmil_last_path)
    torch.save(model.classifier.state_dict(), classifier_last_path)

    if best_state is not None:
        abmil_best_path = checkpoints_dir / f"{args.run_name}_abmil_best.pt"
        classifier_best_path = checkpoints_dir / f"{args.run_name}_classifier_best.pt"
        torch.save(best_state["model"], abmil_best_path)
        torch.save(best_state["classifier"], classifier_best_path)
    else:
        abmil_best_path = None
        classifier_best_path = None

    pd.DataFrame(attention_rows).to_csv(attention_csv, index=False)
    pd.DataFrame(slide_rows).to_csv(slide_csv, index=False)

    metrics_df = pd.DataFrame(history)
    metrics_csv = output_dir / "training_metrics.csv"
    metrics_df.to_csv(metrics_csv, index=False)

    try:
        import matplotlib.pyplot as plt

        epochs = sorted(set(metrics_df["epoch"]))
        def plot_metric(metric: str, ylabel: str, filename: str) -> None:
            plt.figure()
            for split in metrics_df["split"].unique():
                split_df = metrics_df[metrics_df["split"] == split]
                plt.plot(split_df["epoch"], split_df[metric], label=split)
            plt.xlabel("Epoch")
            plt.ylabel(ylabel)
            plt.title(f"{ylabel} over epochs")
            plt.legend()
            plt.grid(True, linestyle="--", alpha=0.4)
            plt.tight_layout()
            plt.savefig(output_dir / filename)
            plt.close()

        if len(epochs) > 0:
            plot_metric("loss", "Loss", "loss_curve.png")
            plot_metric("accuracy", "Accuracy", "accuracy_curve.png")
    except Exception as exc:
        logging.warning("Failed to save plots: %s", exc)

    logging.info("Saved attention weights to %s", attention_csv)
    logging.info("Saved slide vectors to %s", slide_csv)
    logging.info("Saved metrics to %s", metrics_csv)
    logging.info("Saved last ABMIL weights to %s", abmil_last_path)
    logging.info("Saved last classifier weights to %s", classifier_last_path)
    if best_state is not None:
        logging.info("Best epoch: %d | val_loss=%.4f", best_epoch, best_val_loss)
        logging.info("Saved best ABMIL weights to %s", abmil_best_path)
        logging.info("Saved best classifier weights to %s", classifier_best_path)


def parse_args(argv: Sequence[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Train ABMIL classifier on precomputed embeddings.")
    parser.add_argument("--embeddings-csv", type=str, required=True, help="CSV with at least patch_path and embedding_path columns.")
    parser.add_argument("--metadata-csv", type=str, required=True, help="metadata.csv containing Reticulin grades.")
    parser.add_argument("--output-dir", type=str, required=True, help="Directory to store outputs.")
    parser.add_argument("--run-name", type=str, default="abmil", help="Identifier used for checkpoint filenames.")
    parser.add_argument("--epochs", type=int, default=30)
    parser.add_argument("--lr", type=float, default=1e-4)
    parser.add_argument("--weight-decay", type=float, default=1e-4)
    parser.add_argument("--att-dim", type=int, default=256)
    parser.add_argument("--hidden-dim", type=int, default=512)
    parser.add_argument("--dropout", type=float, default=0.25)
    parser.add_argument("--num-classes", type=int, default=4)
    parser.add_argument("--batch-size", type=int, default=1, help="Bags per batch (defaults to 1).")
    parser.add_argument("--device", type=str, default=None, help="Device to use (cuda, mps, cpu).")
    parser.add_argument("--weight-file", type=str, default=None, help="Optional path to load classifier weights.")
    parser.add_argument("--val-ratio", type=float, default=0.2, help="Fraction of slides for validation split.")
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--log-level", type=str, default="INFO")
    return parser.parse_args(argv)


def main(argv: Sequence[str] | None = None) -> None:
    args = parse_args(argv)

    if args.device is None:
        if torch.cuda.is_available():
            args.device = "cuda"
        elif getattr(torch.backends, "mps", None) and torch.backends.mps.is_available():
            args.device = "mps"
        else:
            args.device = "cpu"

    LOG_DIR.mkdir(parents=True, exist_ok=True)
    log_file = LOG_DIR / f"{args.run_name}.log"
    logging.basicConfig(
        level=getattr(logging, args.log_level.upper(), logging.INFO),
        format="%(asctime)s [%(levelname)s] %(message)s",
        handlers=[
            logging.StreamHandler(),
            logging.FileHandler(log_file, mode="w"),
        ],
    )
    logging.info("Writing log to %s", log_file)
    logging.info("Arguments: %s", json.dumps(vars(args), indent=2))

    train(args)


if __name__ == "__main__":
    main()

# node1 has internet
# node3  ssh and then load it there